---
language: python
services: docker

env:
  global:
    - MOLECULE_NO_LOG: "false"
  matrix:
    - MOLECULE_DISTRO: centos:8
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: ubuntu:20.04
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04

# https://github.com/docker/docker-py/issues/2639#issuecomment-671974635
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get purge docker-ce -y
  - sudo apt-get autoremove -y
  - curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/10-docker.sh | sudo bash -s -- install
  - sudo usermod -aG docker $USER
  - curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/10-docker.sh | sudo bash -s -- restart

install:
  # Install test dependencies.
  - pip install molecule docker ansible-lint flake8 testinfra

before_script:
  - cd ../ && mv ansible-openvpnclient juju4.openvpnclient
  - cd juju4.openvpnclient

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
