---

- name: Check if macports is present
  ansible.builtin.stat: path=/opt/local/var/macports
  register: macportsdir
- name: Darwin | Macports openvpn package
  macports: name=openvpn2 state=present update_cache=yes
  when: macportsdir.stat.exists
  register: pkg_result
  until: pkg_result is success

- name: Fix launchd file
  ansible.builtin.template:
    src: org.macports.openvpn2.plist.j2
    dest: /Library/LaunchDaemons/org.macports.openvpn2.plist
    mode: '0644'
    backup: yes
  notify:
    - Openvpn restart - darwin
