---

- name: Check monit status
  ansible.builtin.command: "monit status {{ daemon }}"
  register: monitstatus
  changed_when: false
  ignore_errors: true
  environment:
    PATH: /usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/local/bin

- name: Force monitor of {{ daemon }}
  ansible.builtin.command: "monit monitor {{ item }}"
  when: "'unmonitor' in monitstatus.stdout"
  environment:
    PATH: /usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/local/bin
