---

- name: Verify
  hosts: openvpnclient
  vars:
    verify_pkgs:
      - openvpn
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that:
          - ansible_facts.packages[item] is defined
      with_items: "{{ verify_pkgs }}"

    - name: Ensure binary is present
      ansible.builtin.stat:
        path: /usr/sbin/openvpn
      register: bin
    - name: Validate bin present
      ansible.builtin.assert:
        that: bin.stat.exists and bin.stat.size != 0 and bin.stat.mode == '0755'
